apiVersion: apps/v1
kind: Deployment
metadata:
  name: myportfolio2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myportfolio2
  template:
    metadata:
      labels:
        app: myportfolio2
    spec:
      containers:
      - name: myportfolio2
        image: prete88/myportfolio2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myportfolio2-service
spec:
  type: NodePort
  selector:
    app: myportfolio2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001